### ISSUE TITLE
Jobs stay queued until the previous job has finished

### ISSUE THREAD

**Issue by jarnolaitinen** [elixir-cloud-aai/cwl-WES#98] opened 2019-04-17 09:46 UTC
I am not sure if this is WES or TES implementation bug or feature.

If I submit a job via Swagger Web UI, it stays in "QUEUED" state as long as the previous job is in "running" state. I would like to get multiple parallel jobs running.

The WES instance submits the jobs to CSC's TESK instance (OpenShift). Please ask for more details via email.

**Comment by aniewielska** [comment] 2019-05-15 10:57
The easy way to check from the user perspective, if the workflow got stuck in WES or TES is to see , if it produced tasks.
If you cannot see any tasks in the logs of the GET endpoint - the workflow is queuing in WES (most probably on single celery worker - the other one may be occupied with running a different workflow - sometimes forever - see below). 
If you can see tasks - you should find a task in QUEUED state. If it so - the problem is most probably at TES side (for instance K8s Jobs pending, because quota was exceeded).
If you can see tasks and they seem to be running forever, it might be WES again losing track of the workflow status (I observe it quite often in EBI, when infrastructure crashes - a temporary loss of connection to DB and/or queue does not heal and the status of the workflow does not ever conclude).

**Comment by uniqueg** [comment] 2019-09-01 04:15
This was actually not quite correct, I think. Parallel jobs could be issued fine, as long as nothing broke. There are some cases where WES-ELIXIR crashes where it should handle errors gracefully. I will leave this issue open to remind myself to check for this in the future, but I expect that it will be resolved in the next re-factoring section (which would get rid of the fickle task monitoring that causes most instabilities as far as I can see).

**Comment by uniqueg** [comment] 2020-04-20 01:52
Haven't seen this happening for quite a while, so will close for now.

**Closed by uniqueg** 2020-04-20 01:52 UTC
